{
    parserClass="com.github.openhab.language.things.parser.ThingsParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Things"
    psiImplClassSuffix="Impl"
    psiPackage="com.github.openhab.language.things.psi"
    psiImplPackage="com.github.openhab.language.things.psi.impl"

    elementTypeHolderClass="com.github.openhab.language.things.psi.ThingsTypes"
    elementTypeClass="com.github.openhab.language.things.psi.ThingsElementType"
    tokenTypeClass="com.github.openhab.language.things.psi.ThingsTokenType"

    psiImplUtilClass="com.github.openhab.language.things.psi.impl.ThingsPsiImplUtil"

    tokens = [
        STRING_LITERAL='regexp:"([^"]|"")*"'
        IDENTIFIER_STRING='regexp:[a-zA-Z][a-zA-Z0-9_-]*'
        NUMBER_LITERAL='regexp:[0-9]+'
        WHITE_SPACE='regexp:\s+'

        ET="@"
        COLON=":"
        COMMA=","
        LEFT_PAREN="("
        RIGHT_PAREN=")"
        LEFT_BRACE="{"
        RIGHT_BRACE="}"
        LEFT_BRACKET="["
        RIGHT_BRACKET="]"
        LESS_THAN="<"
        MORE_THAN=">"
        EQUALS="="
    ]
}

ThingsFile             ::= ItemThings_*
private ItemThings_    ::= (ThingItem|COMMENT|CRLF)

BINDING_ID_KEYWORD     ::= IDENTIFIER_STRING
TYPE_ID_KEYWORD        ::= IDENTIFIER_STRING
THING_ID_KEYWORD       ::= IDENTIFIER_STRING

BindingType            ::= BINDING_ID_KEYWORD COLON TYPE_ID_KEYWORD COLON THING_ID_KEYWORD

ParameterKey           ::= IDENTIFIER_STRING

ParameterStringValue   ::= STRING_LITERAL
ParameterNumberValue   ::= NUMBER_LITERAL
ParameterValue         ::= (ParameterStringValue|ParameterNumberValue)
Parameter              ::= ParameterKey EQUALS ParameterValue
ParameterList          ::= Parameter (COMMA ParameterList)*

Label                  ::= STRING_LITERAL
Location               ::= STRING_LITERAL

ThingKeyword           ::= IDENTIFIER_STRING
ThingItem              ::= ThingKeyword BindingType Label? ET? Location? LEFT_BRACKET ParameterList RIGHT_BRACKET