name: Manually release

on: workflow_dispatch

jobs:
  manual_release:
    runs-on: ubuntu-latest
    steps:
      - name: Сheckout master
        uses: actions/checkout@master
      - name: Merge develop -> master
        uses: everlytic/branch-merge@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'develop'
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
